import React, { useState } from "react";
import { Link } from "react-router-dom";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { forgotPasswordSchema } from "shared";
import { api } from "../lib/apiClient.js";
import { Sprout, Mail, CheckCircle, AlertCircle, ArrowLeft } from "lucide-react";
import { z } from "zod";

type ForgotFormInputs = z.infer<typeof forgotPasswordSchema>;

export const ForgotPasswordPage: React.FC = () => {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [apiError, setApiError] = useState<string | null>(null);
  const [successLink, setSuccessLink] = useState<string | null>(null);
  const [showSuccess, setShowSuccess] = useState(false);

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<ForgotFormInputs>({
    resolver: zodResolver(forgotPasswordSchema),
  });

  const onSubmit = async (data: ForgotFormInputs) => {
    setApiError(null);
    setIsSubmitting(true);
    setSuccessLink(null);
    try {
      const res = await api.auth.forgotPassword(data);
      // In development mode, the backend returns the dev link in the payload
      if (res?.devResetLink) {
        setSuccessLink(res.devResetLink);
      }
      setShowSuccess(true);
    } catch (err: any) {
      setApiError(err.message || "Failed to submit request.");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8 font-sans">
      <div className="sm:mx-auto sm:w-full sm:max-w-md text-center">
        <Link to="/" className="inline-flex items-center space-x-2">
          <Sprout className="w-10 h-10 text-emerald-600" />
          <span className="font-extrabold text-2xl tracking-wide text-slate-900">AgriGuide</span>
        </Link>
        <h2 className="mt-6 text-3xl font-extrabold text-slate-900 font-sans">Reset your password</h2>
        <p className="mt-2 text-sm text-slate-655 font-medium">
          Enter your email address and we will dispatch a secure reset link.
        </p>
      </div>

      <div className="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
        <div className="bg-white py-8 px-4 shadow sm:rounded-2xl sm:px-10 border border-slate-200">
          {showSuccess ? (
            <div className="space-y-5 text-center">
              <div className="bg-emerald-50 text-emerald-800 p-4 rounded-xl border border-emerald-250 flex items-start space-x-3 text-left">
                <CheckCircle className="w-6 h-6 text-emerald-600 shrink-0 mt-0.5" />
                <div>
                  <span className="font-bold text-sm block">Reset request dispatched</span>
                  <span className="text-xs text-emerald-900">
                    If matching account records are found, a password reset link has been dispatched to your email address. Expiration period is 1 hour.
                  </span>
                </div>
              </div>

              {successLink && (
                <div className="bg-slate-50 p-4 rounded-xl border border-slate-200 text-left space-y-2">
                  <span className="font-bold text-xs text-slate-500 uppercase tracking-wide block">Development Environment Hook:</span>
                  <p className="text-xs text-slate-600 font-medium">
                    Because SMTP is unconfigured in development, click the direct reset link generated by the server:
                  </p>
                  <a
                    href={successLink}
                    className="text-xs font-bold text-emerald-600 hover:text-emerald-700 break-all block underline"
                  >
                    {successLink}
                  </a>
                </div>
              )}

              <div className="pt-2">
                <Link
                  to="/login"
                  className="inline-flex items-center space-x-2 text-emerald-600 hover:text-emerald-700 font-bold text-sm"
                >
                  <ArrowLeft className="w-4 h-4" />
                  <span>Back to Sign In</span>
                </Link>
              </div>
            </div>
          ) : (
            <form className="space-y-6" onSubmit={handleSubmit(onSubmit)}>
              {apiError && (
                <div className="bg-red-50 border border-red-200 rounded-xl p-4 flex items-start space-x-3" role="alert">
                  <AlertCircle className="w-5 h-5 text-red-600 shrink-0 mt-0.5" />
                  <span className="text-sm font-medium text-red-800">{apiError}</span>
                </div>
              )}

              <div>
                <label htmlFor="email" className="block text-sm font-semibold text-slate-700">
                  Email address
                </label>
                <div className="mt-1 relative">
                  <input
                    id="email"
                    type="email"
                    {...register("email")}
                    className={`appearance-none block w-full px-3 py-2.5 border rounded-lg shadow-sm placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 sm:text-sm ${
                      errors.email ? "border-red-300 ring-1 ring-red-350" : "border-slate-350"
                    }`}
                    placeholder="name@example.com"
                  />
                </div>
                {errors.email && (
                  <p className="mt-1.5 text-xs font-semibold text-red-600">{errors.email.message}</p>
                )}
              </div>

              <div>
                <button
                  type="submit"
                  disabled={isSubmitting}
                  className="w-full flex justify-center py-2.5 px-4 border border-transparent rounded-lg shadow-md text-sm font-bold text-white bg-emerald-600 hover:bg-emerald-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-emerald-500 disabled:opacity-50 disabled:cursor-not-allowed transition-all uppercase tracking-wider"
                >
                  {isSubmitting ? (
                    <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                  ) : (
                    "Request Reset Link"
                  )}
                </button>
              </div>

              <div className="flex justify-center border-t border-slate-100 pt-4">
                <Link
                  to="/login"
                  className="flex items-center space-x-1 text-slate-500 hover:text-slate-800 text-xs font-semibold transition-colors"
                >
                  <ArrowLeft className="w-4 h-4" />
                  <span>Return to Sign In</span>
                </Link>
              </div>
            </form>
          )}
        </div>
      </div>
    </div>
  );
};
export default ForgotPasswordPage;
